# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('reciever', models.CharField(max_length=120)),
                ('reciever_phone', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 1, 16, 10, 46, 13, 418611, tzinfo=utc))),
                ('body', models.TextField()),
            ],
        ),
    ]
