# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0002_auto_20160116_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 10, 54, 54, 345117, tzinfo=utc)),
        ),
    ]
