# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0003_auto_20160116_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 1, 11, 626370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='reciever_phone',
            field=models.CharField(max_length=80),
        ),
    ]
