# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0006_auto_20160116_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='r_phone',
            new_name='reciever_phone',
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 6, 27, 215038, tzinfo=utc)),
        ),
    ]
