# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0007_auto_20160116_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='reciever_address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 7, 55, 219187, tzinfo=utc)),
        ),
    ]
