# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0008_auto_20160116_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 8, 57, 329178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='reciever_address',
            field=models.CharField(max_length=120),
        ),
    ]
