# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0012_auto_20160116_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 11, 26, 782592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default='Tên người gửi', max_length=120),
        ),
    ]
