# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0013_auto_20160116_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(default='Địa chỉ người gửi', max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='body',
            field=models.TextField(default='Nội dung'),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 13, 21, 889659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(default='Số điện thoại người gửi', max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='reciever',
            field=models.CharField(default='Tên người nhận', max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='reciever_address',
            field=models.CharField(default='Địa chỉ người nhận', max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='reciever_phone',
            field=models.CharField(default='Số điện thoại người nhận', max_length=80),
        ),
    ]
