# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0017_auto_20160116_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 11, 23, 36, 829169, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
