# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0023_auto_20160116_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='time_send',
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 13, 7, 3, 170543, tzinfo=utc), editable=False),
        ),
    ]
