# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0025_auto_20160116_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 14, 37, 55, 71355, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
