# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0026_auto_20160116_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 14, 42, 33, 64982, tzinfo=utc), editable=False),
        ),
    ]
