# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0040_auto_20160116_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='code',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 15, 34, 12, 674840, tzinfo=utc), editable=False),
        ),
    ]
