# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0046_auto_20160116_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 15, 37, 33, 796920, tzinfo=utc), editable=False),
        ),
    ]
