# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0058_auto_20160116_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 17, 18, 39, 451239, tzinfo=utc), editable=False),
        ),
    ]
