# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0081_auto_20160117_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 17, 7, 42, 59, 522847, tzinfo=utc), editable=False),
        ),
    ]
