# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0101_auto_20160117_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('captcha', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 8, 49, 11, 47031, tzinfo=utc)),
        ),
    ]
