# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0102_auto_20160118_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 9, 0, 16, 926271, tzinfo=utc)),
        ),
    ]
