# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0106_auto_20160118_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 9, 27, 46, 603197, tzinfo=utc)),
        ),
    ]
