# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0109_auto_20160118_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 10, 11, 30, 167388, tzinfo=utc)),
        ),
    ]
