# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0110_auto_20160118_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 11, 19, 48, 355630, tzinfo=utc)),
        ),
    ]
