# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0115_auto_20160118_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 12, 30, 24, 534918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 12, 30, 24, 534918, tzinfo=utc), editable=False),
        ),
    ]
