# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0129_auto_20160119_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 17, 40, 7, 976392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(default='auth.User', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 17, 40, 7, 976392, tzinfo=utc), editable=False),
        ),
    ]
