# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0130_auto_20160119_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 17, 51, 23, 156822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 17, 51, 23, 156822, tzinfo=utc), editable=False),
        ),
    ]
