# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0135_auto_20160119_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 54, 45, 720449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 54, 45, 720449, tzinfo=utc), editable=False),
        ),
    ]
