# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0144_auto_20160119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 9, 22, 58, 642841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 9, 22, 58, 642841, tzinfo=utc), editable=False),
        ),
    ]
