# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0148_auto_20160119_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 10, 1, 29, 327193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 10, 1, 29, 328193, tzinfo=utc), editable=False),
        ),
    ]
