# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0156_auto_20160120_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 5, 25, 38, 127361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 5, 25, 38, 128361, tzinfo=utc), editable=False),
        ),
    ]
