# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiperapp', '0160_auto_20160120_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 6, 27, 17, 102657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 6, 27, 17, 103658, tzinfo=utc), editable=False),
        ),
    ]
